pepe = {
    'die': 'CAACAgIAAxkBAAEGLBFjVGJ76EOHLXzJiRSNb-ywZD19IAACkgEAAonq5QcjCcbKL6NW8yoE',
    'happy': 'CAACAgIAAxkBAAEGLBNjVGKjmz7Z42HqBHARpIdwBt-twQACbQEAAonq5QeQ9Vt1jHr5yyoE',
    'angry': 'CAACAgIAAxkBAAEGLA9jVGJepCTY2pXMvGTwo2ZjivZ_mQACTAEAAonq5QcmOMdrO1Q6TSoE',
    'ready': 'CAACAgIAAxkBAAEGLt1jVYZu6aWxm4PUBmPzIU_1TqHogAACdgEAAonq5QfGntvLIQzPUCoE',
    'sad': 'CAACAgIAAxkBAAEGLt9jVYdXYw9Hq9M14NjwkbjfDLyeswACWAEAAonq5QeMeUNGvbmmRioE',
}
